# Generated by Django 4.0 on 2021-12-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeShopApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='tamanho',
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
