# Generated by Django 4.0 on 2021-12-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeShopApp', '0002_remove_produto_tamanho_produto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='foto_produto',
            field=models.ImageField(blank=True, upload_to='fotos/s'),
        ),
    ]
